### ISSUE TITLE
Could you please link to sevenbridges-python from your readme?

### ISSUE THREAD

**Issue by jackDiGi** [sbg/dreamwebinars#1]
You have a nice section here:

> Helper Functions
> 
> dream_helpers.py is a library of helper functions to be used with the Python client of the Seven Bridges API. These functions are used in each notebook. It may be helpful to look through these functions to understand how API calls are made using the Python client.

It would be excellent if we can direct traffic to https://github.com/sbg/sevenbridges-python, ideally linking from the first sentence. We can then link back to these dreamwebinars from the tutorials readme of okAPI (@emyo). Then we can keep all these resources _harmonized_ :)

**Comment by emyo** [comment]
@jackDiGi added to the Dream challenge public project page here: http://docs.cancergenomicscloud.org/v1.0/docs/dream-challenge#section-learn-more :)

**Comment by gaurav-kaushik** [comment]
Thanks @jackDiGi and @emyo! PR merged :)
